require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2 # testing PATCH #update with invalid attributes
