require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2 # testing PATCH #update with invalid attributes

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
