require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  # TargetRubyVersion: 2.7.2
  # Exclude:
  #   - db/**/*
  #   - config/**/*
  #   - bin/**/*
  #   - node_modules/**/*
  #   - !ruby/regexp /old_and_unused\.rb$/

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false
